### ISSUE TITLE
Research game idea

### ISSUE THREAD

**Issue by quan-dao-99** [dendimaniac/summer-game-project#1]
**AI**

- Research **the potential of AI,** using movies, games, news, books, etc.

**Deadline**

- 19/5/2019

**Comment by vu-dao-93** [comment]
Puzzle game: The player train robots to do housework. Each day they'll follow the exact instruction the player did the day before. The player has to do the next task in a way that doesn't conflict with the robots carrying out older tasks
https://dinopoloclub.com/minimetro/

**Comment by vu-dao-93** [comment]
Stealth platformer: In a universe where public opinion is against using patients data for AI research without consent, a thief needs to break into many hospitals to take data about cancer patients. His motive was unknown until the end that he develops a method to treat cancer for his mom.

**Comment by vu-dao-93** [comment]
Final idea: 
Puzzle game: The player train robots to do housework. Each day they'll follow the exact instruction the player did the day before. The player has to do the next task in a way that doesn't conflict with the robots carrying out older tasks
